import streamlit as streamlit
streamlit.subheader("The Endocannabinoid System Research Company - Chemical Sensing Initiative")
streamlit.header("The Holy Grace:")
streamlit.text("Haemoglobin-in-action is might in the extension of self.")
streamlit.text("Nitric Oxide is preservation to the grounds of further construction.")
streamlit.text("Endocannabinoid is vision of the Ionization.")
streamlit.text("Know the spread of the company in geophysics, geopolitics, and geographic information systems.")
streamlit.text("Roy creating cannabinoid-hardened-steel is Darkwater.")
streamlit.subheader("The Cannabinoid to Endocannabinoid Exchange:")
streamlit.text("-Haemoglobin")
streamlit.text("-Nitric Oxide")
streamlit.text("-Endocannabinoid")
streamlit.subheader("Run biochemic analysis.")
streamlit.text("Remember Artificial Intelligence for any contact with the company.")
streamlit.text("Love thy neighbor.")