[github]
token = "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"
username = "EllisDylanP"
repo = "ESRC"
branch = "master"
file_path = "Username and Password.csv"
file_path2 = "Activity.csv"
